/*
 * Copyright 2020 Hochikong
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.hochikong.ktmeta.swingui;

import com.formdev.flatlaf.intellijthemes.FlatCarbonIJTheme;

import javax.swing.*;
import javax.swing.tree.DefaultMutableTreeNode;
import java.awt.image.BufferedImage;

/**
 *
 * @author ckhoi
 */
public class KtmetaJFrameMain extends javax.swing.JFrame {

    /**
     * Creates new form KtmetaJFrame
     */
    public KtmetaJFrameMain() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainToolBar = new javax.swing.JToolBar();
        AddDatabaseBTN = new javax.swing.JButton();
        AddIndexBTN = new javax.swing.JButton();
        MainSplitPane = new javax.swing.JSplitPane();
        SubLeftTabbedPane = new javax.swing.JTabbedPane();
        LTScrollPane = new javax.swing.JScrollPane();
        DefaultMutableTreeNode dbms = new DefaultMutableTreeNode("DBMS");
        DefaultMutableTreeNode sqlite = new DefaultMutableTreeNode("SQLite");
        DefaultMutableTreeNode postgresql = new DefaultMutableTreeNode("PostgreSQL");
        dbms.add(sqlite);
        dbms.add(postgresql);
        LibraryTree = new javax.swing.JTree(dbms);
        ESScrollPane = new javax.swing.JScrollPane();
        DefaultMutableTreeNode ElasticSearchIndices = new DefaultMutableTreeNode("ElasticSearch Indices");
        IndicesTree = new javax.swing.JTree(ElasticSearchIndices);
        SubRightSplitPane = new javax.swing.JSplitPane();
        CentreSplit = new javax.swing.JPanel();
        GeneralTabbedPaneTemplate = new javax.swing.JTabbedPane();
        GeneralSplitPaneTemplate = new javax.swing.JSplitPane();
        GeneralUpTabbedPaneTemplate = new javax.swing.JScrollPane();
        GeneralDownTabbedPaneTemplate = new javax.swing.JTabbedPane();
        QueryScrollPane = new javax.swing.JScrollPane();
        InfoScrollPane = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        RightSplit = new javax.swing.JPanel();
        MainMenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        EditMenu = new javax.swing.JMenu();
        ToolsMenu = new javax.swing.JMenu();
        ToolsPrefItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();
        HelpAboutItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ktmeta");
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(1440, 900));
        setName("MainFrame"); // NOI18N
        setSize(new java.awt.Dimension(1920, 1080));

        MainToolBar.setRollover(true);

        AddDatabaseBTN.setText("Add DB");
        AddDatabaseBTN.setFocusable(false);
        AddDatabaseBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddDatabaseBTN.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MainToolBar.add(AddDatabaseBTN);

        AddIndexBTN.setText("Add Index");
        AddIndexBTN.setFocusable(false);
        AddIndexBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddIndexBTN.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AddIndexBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddIndexBTNActionPerformed(evt);
            }
        });
        MainToolBar.add(AddIndexBTN);

        MainSplitPane.setOneTouchExpandable(true);

        SubLeftTabbedPane.setMinimumSize(new java.awt.Dimension(200, 100));
        SubLeftTabbedPane.setPreferredSize(new java.awt.Dimension(250, 100));

        LTScrollPane.setViewportView(LibraryTree);

        SubLeftTabbedPane.addTab("DB Libraries", LTScrollPane);

        ESScrollPane.setViewportView(IndicesTree);

        SubLeftTabbedPane.addTab("ES Indices", ESScrollPane);

        MainSplitPane.setLeftComponent(SubLeftTabbedPane);

        SubRightSplitPane.setOneTouchExpandable(true);

        CentreSplit.setMinimumSize(new java.awt.Dimension(900, 100));
        CentreSplit.setPreferredSize(new java.awt.Dimension(1280, 700));

        GeneralTabbedPaneTemplate.setPreferredSize(new java.awt.Dimension(1100, 719));

        GeneralSplitPaneTemplate.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        GeneralUpTabbedPaneTemplate.setPreferredSize(new java.awt.Dimension(900, 600));
        GeneralSplitPaneTemplate.setLeftComponent(GeneralUpTabbedPaneTemplate);

        GeneralDownTabbedPaneTemplate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        GeneralDownTabbedPaneTemplate.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        GeneralDownTabbedPaneTemplate.addTab("Universal Query", QueryScrollPane);

        jTextPane1.setEditable(false);
        InfoScrollPane.setViewportView(jTextPane1);

        GeneralDownTabbedPaneTemplate.addTab("Info Output", InfoScrollPane);

        GeneralSplitPaneTemplate.setRightComponent(GeneralDownTabbedPaneTemplate);

        GeneralTabbedPaneTemplate.addTab("tab1", GeneralSplitPaneTemplate);

        javax.swing.GroupLayout CentreSplitLayout = new javax.swing.GroupLayout(CentreSplit);
        CentreSplit.setLayout(CentreSplitLayout);
        CentreSplitLayout.setHorizontalGroup(
                CentreSplitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(GeneralTabbedPaneTemplate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CentreSplitLayout.setVerticalGroup(
                CentreSplitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(GeneralTabbedPaneTemplate, javax.swing.GroupLayout.DEFAULT_SIZE, 981, Short.MAX_VALUE)
        );

        SubRightSplitPane.setLeftComponent(CentreSplit);

        javax.swing.GroupLayout RightSplitLayout = new javax.swing.GroupLayout(RightSplit);
        RightSplit.setLayout(RightSplitLayout);
        RightSplitLayout.setHorizontalGroup(
                RightSplitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        RightSplitLayout.setVerticalGroup(
                RightSplitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 981, Short.MAX_VALUE)
        );

        SubRightSplitPane.setRightComponent(RightSplit);

        MainSplitPane.setRightComponent(SubRightSplitPane);

        FileMenu.setText("File");
        MainMenuBar.add(FileMenu);

        EditMenu.setText("Edit");
        MainMenuBar.add(EditMenu);

        ToolsMenu.setText("Tools");

        ToolsPrefItem.setIcon(new ImageIcon(new BufferedImage(20, 20, BufferedImage.TYPE_INT_ARGB)));
        ToolsPrefItem.setText("Preference");
        ToolsPrefItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToolsPrefItemActionPerformed(evt);
            }
        });
        ToolsMenu.add(ToolsPrefItem);
        ToolsMenu.add(jSeparator2);

        jMenuItem1.setIcon(new ImageIcon(new BufferedImage(20, 20, BufferedImage.TYPE_INT_ARGB)));
        jMenuItem1.setText("ElasticSearch");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        ToolsMenu.add(jMenuItem1);

        MainMenuBar.add(ToolsMenu);

        HelpMenu.setText("Help");

        HelpAboutItem.setIcon(new ImageIcon(new BufferedImage(20, 20, BufferedImage.TYPE_INT_ARGB)));
        HelpAboutItem.setText("About");
        HelpAboutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpAboutItemActionPerformed(evt);
            }
        });
        HelpMenu.add(HelpAboutItem);

        MainMenuBar.add(HelpMenu);

        setJMenuBar(MainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MainToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MainSplitPane)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(MainToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(MainSplitPane)
                                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ToolsPrefItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToolsPrefItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToolsPrefItemActionPerformed

    private void AddIndexBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddIndexBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddIndexBTNActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void HelpAboutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpAboutItemActionPerformed
        KtHelpAboutItemActionPerformed(evt);
    }//GEN-LAST:event_HelpAboutItemActionPerformed

    /**
     * Kotlin override functions
     */
    protected void KtHelpAboutItemActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Install theme */
        FlatCarbonIJTheme.install();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KtmetaJFrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton AddDatabaseBTN;
    protected javax.swing.JButton AddIndexBTN;
    protected javax.swing.JPanel CentreSplit;
    protected javax.swing.JScrollPane ESScrollPane;
    protected javax.swing.JMenu EditMenu;
    protected javax.swing.JMenu FileMenu;
    protected javax.swing.JTabbedPane GeneralDownTabbedPaneTemplate;
    protected javax.swing.JSplitPane GeneralSplitPaneTemplate;
    protected javax.swing.JTabbedPane GeneralTabbedPaneTemplate;
    protected javax.swing.JScrollPane GeneralUpTabbedPaneTemplate;
    protected javax.swing.JMenuItem HelpAboutItem;
    protected javax.swing.JMenu HelpMenu;
    protected javax.swing.JTree IndicesTree;
    protected javax.swing.JScrollPane InfoScrollPane;
    protected javax.swing.JScrollPane LTScrollPane;
    protected javax.swing.JTree LibraryTree;
    protected javax.swing.JMenuBar MainMenuBar;
    protected javax.swing.JSplitPane MainSplitPane;
    protected javax.swing.JToolBar MainToolBar;
    protected javax.swing.JScrollPane QueryScrollPane;
    protected javax.swing.JPanel RightSplit;
    protected javax.swing.JTabbedPane SubLeftTabbedPane;
    private javax.swing.JSplitPane SubRightSplitPane;
    protected javax.swing.JMenu ToolsMenu;
    protected javax.swing.JMenuItem ToolsPrefItem;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
