/*
 * Copyright 2020 Hochikong
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.hochikong.ktmeta.testOnly;

import com.formdev.flatlaf.intellijthemes.FlatSolarizedLightIJTheme;
import io.github.hochikong.ktmeta.swingui.essentials.SimpleResultPanelContainer;

import javax.swing.*;
import javax.swing.table.TableModel;
import java.nio.charset.StandardCharsets;
import java.util.Random;

/**
 *
 * @author ckhoi
 */
public class ResultPanelContainerTest extends javax.swing.JFrame {

    /**
     * Creates new form ResultPanelContainerTest
     */
    public ResultPanelContainerTest() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPaneQueryResult = new javax.swing.JTabbedPane();
        PanelResultTemplate = new javax.swing.JPanel();
        PanelResultToolbar = new javax.swing.JPanel();
        BTNGotoFirstPage = new javax.swing.JButton();
        BTNGotoPreviousPage = new javax.swing.JButton();
        SpinnerMaxRows = new javax.swing.JSpinner();
        LabelResultRows = new javax.swing.JLabel();
        BTNGotoNextPage = new javax.swing.JButton();
        BTNGotoLastPage = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        BTNRefresh = new javax.swing.JButton();
        SRPScrollPane = new javax.swing.JScrollPane();
        TableResult = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabbedPaneQueryResult.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TabbedPaneQueryResult.setPreferredSize(new java.awt.Dimension(900, 650));

        PanelResultToolbar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 131, 201)));

        BTNGotoFirstPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ico/16pix/angle-double-left.png"))); // NOI18N
        BTNGotoFirstPage.setToolTipText("First page");
        BTNGotoFirstPage.setFocusable(false);

        BTNGotoPreviousPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ico/16pix/angle-left.png"))); // NOI18N
        BTNGotoPreviousPage.setToolTipText("Previous page");
        BTNGotoPreviousPage.setFocusable(false);

        LabelResultRows.setText("0-20 of 100 results");
        LabelResultRows.setToolTipText("");

        BTNGotoNextPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ico/16pix/angle-right.png"))); // NOI18N
        BTNGotoNextPage.setToolTipText("Next page");
        BTNGotoNextPage.setFocusable(false);

        BTNGotoLastPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ico/16pix/angle-double-right.png"))); // NOI18N
        BTNGotoLastPage.setToolTipText("Last page");
        BTNGotoLastPage.setFocusable(false);

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        BTNRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ico/16pix/sync-alt.png"))); // NOI18N
        BTNRefresh.setToolTipText("Refresh");
        BTNRefresh.setFocusable(false);

        javax.swing.GroupLayout PanelResultToolbarLayout = new javax.swing.GroupLayout(PanelResultToolbar);
        PanelResultToolbar.setLayout(PanelResultToolbarLayout);
        PanelResultToolbarLayout.setHorizontalGroup(
            PanelResultToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelResultToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNGotoFirstPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNGotoPreviousPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpinnerMaxRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelResultRows)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNGotoNextPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNGotoLastPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNRefresh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelResultToolbarLayout.setVerticalGroup(
            PanelResultToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelResultToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelResultToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTNRefresh)
                    .addGroup(PanelResultToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BTNGotoLastPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNGotoNextPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNGotoFirstPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNGotoPreviousPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SpinnerMaxRows, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(LabelResultRows, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TableResult.setAutoCreateRowSorter(true);
        TableResult.setModel(this.injectModel);
        TableResult.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TableResult.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        SRPScrollPane.setViewportView(TableResult);

        javax.swing.GroupLayout PanelResultTemplateLayout = new javax.swing.GroupLayout(PanelResultTemplate);
        PanelResultTemplate.setLayout(PanelResultTemplateLayout);
        PanelResultTemplateLayout.setHorizontalGroup(
            PanelResultTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelResultToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SRPScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
        );
        PanelResultTemplateLayout.setVerticalGroup(
            PanelResultTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelResultTemplateLayout.createSequentialGroup()
                .addComponent(PanelResultToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SRPScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
        );

        TabbedPaneQueryResult.addTab("Search result template", PanelResultTemplate);

        jButton1.setText("Add tab");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TabbedPaneQueryResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 187, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TabbedPaneQueryResult, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SimpleResultPanelContainer sp = new SimpleResultPanelContainer();
        TabbedPaneQueryResult.addTab("test", sp);
        JPanel x = TestCloseBTNHelper.buildCustomTabHeadPanel("test", "204,225,152", "238,232,213");
        TabbedPaneQueryResult.setTabComponentAt(TabbedPaneQueryResult.indexOfComponent(sp), x);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        FlatSolarizedLightIJTheme.install();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultPanelContainerTest().setVisible(true);
            }
        });
    }
    
    private final TableModel injectModel = new javax.swing.table.DefaultTableModel(
            new Object[][]{
                {getRandomString(), getRandomString()},
                {getRandomString(), getRandomString()}
            },
            new String[]{
                "Result : ", "Match on : "
            }
    );

    private String getRandomString() {
        byte[] array = new byte[7]; // length is bounded by 7
        new Random().nextBytes(array);
        return new String(array, StandardCharsets.UTF_8);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton BTNGotoFirstPage;
    protected javax.swing.JButton BTNGotoLastPage;
    protected javax.swing.JButton BTNGotoNextPage;
    protected javax.swing.JButton BTNGotoPreviousPage;
    protected javax.swing.JButton BTNRefresh;
    protected javax.swing.JLabel LabelResultRows;
    protected javax.swing.JPanel PanelResultTemplate;
    protected javax.swing.JPanel PanelResultToolbar;
    private javax.swing.JScrollPane SRPScrollPane;
    protected javax.swing.JSpinner SpinnerMaxRows;
    protected javax.swing.JTabbedPane TabbedPaneQueryResult;
    protected javax.swing.JTable TableResult;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
