/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.hochikong.ktmeta.swingui.dialogs;

import com.formdev.flatlaf.intellijthemes.FlatSolarizedLightIJTheme;
import java.awt.Image;
import javax.swing.JRootPane;

/**
 *
 * @author ckhoi
 */
public class SetESMapping extends javax.swing.JDialog {

    /**
     * Creates new form NewMapping
     */
    public SetESMapping(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        HideHead();
    }
    
    public SetESMapping(java.awt.Frame parent, boolean modal, Image icon) {
        super(parent, modal);
        initComponents();
        HideHead();
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelESHost = new javax.swing.JLabel();
        TextFieldESHost = new javax.swing.JTextField();
        LabelESPort = new javax.swing.JLabel();
        LabelESIndex = new javax.swing.JLabel();
        TextFieldESIndex = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaJSONSample = new javax.swing.JTextArea();
        BTNCreateMapping = new javax.swing.JButton();
        BTNResetMapping = new javax.swing.JButton();
        BTNClearTextArea = new javax.swing.JButton();
        SpinnerESPort = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("i18n/Dialogs/SetESMapping_trans"); // NOI18N
        setTitle(bundle.getString("CREATE MAPPING BY JSON DOCUMENT SAMPLE")); // NOI18N
        setUndecorated(true);

        LabelESHost.setText(bundle.getString("ELASTICSEARCH HOST :")); // NOI18N

        TextFieldESHost.setForeground(new java.awt.Color(204, 204, 204));
        TextFieldESHost.setText("localhost");
        TextFieldESHost.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldESHostFocusGained(evt);
            }
        });

        LabelESPort.setText(bundle.getString("ELASTICSEARCH PORT :")); // NOI18N

        LabelESIndex.setText(bundle.getString("ES INDEX: ")); // NOI18N

        TextFieldESIndex.setForeground(new java.awt.Color(204, 204, 204));
        TextFieldESIndex.setText("TargetIndex");
        TextFieldESIndex.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldESIndexFocusGained(evt);
            }
        });

        TextAreaJSONSample.setColumns(20);
        TextAreaJSONSample.setRows(5);
        TextAreaJSONSample.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Paste your sample document here", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei UI", 0, 12), new java.awt.Color(74, 136, 199))); // NOI18N
        jScrollPane1.setViewportView(TextAreaJSONSample);

        BTNCreateMapping.setText(bundle.getString("CREATE MAPPING BY SAMPLE")); // NOI18N
        BTNCreateMapping.setFocusable(false);
        BTNCreateMapping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCreateMappingActionPerformed(evt);
            }
        });

        BTNResetMapping.setText(bundle.getString("DROP INDEX AND RESET MAPPING BY SAMPLE")); // NOI18N
        BTNResetMapping.setFocusable(false);
        BTNResetMapping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNResetMappingActionPerformed(evt);
            }
        });

        BTNClearTextArea.setText(bundle.getString("CLEAR")); // NOI18N
        BTNClearTextArea.setFocusable(false);
        BTNClearTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNClearTextAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelESHost)
                            .addComponent(LabelESPort)
                            .addComponent(LabelESIndex))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextFieldESHost)
                            .addComponent(TextFieldESIndex, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                            .addComponent(SpinnerESPort)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BTNCreateMapping)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(BTNResetMapping)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNClearTextArea))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelESHost)
                    .addComponent(TextFieldESHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelESPort)
                    .addComponent(SpinnerESPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldESIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelESIndex))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNCreateMapping)
                    .addComponent(BTNResetMapping)
                    .addComponent(BTNClearTextArea))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNCreateMappingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCreateMappingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNCreateMappingActionPerformed

    private void BTNResetMappingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNResetMappingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNResetMappingActionPerformed

    private void BTNClearTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNClearTextAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNClearTextAreaActionPerformed

    private void TextFieldESHostFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldESHostFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldESHostFocusGained

    private void TextFieldESIndexFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldESIndexFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldESIndexFocusGained
    //</Auto-Generate>
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatSolarizedLightIJTheme.install();
        
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SetESMapping dialog = new SetESMapping(new javax.swing.JFrame(), true);
                dialog.setLocationRelativeTo(null);
                
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.TextAreaJSONSample.requestFocusInWindow();
                dialog.setVisible(true);
            }
        });
    }
    
    //<My-Custom>
    protected void HideHead(){
        // Like IDEA style
        this.getRootPane().setWindowDecorationStyle(JRootPane.FRAME);
    }
    //</My-Custom>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton BTNClearTextArea;
    protected javax.swing.JButton BTNCreateMapping;
    protected javax.swing.JButton BTNResetMapping;
    private javax.swing.JLabel LabelESHost;
    private javax.swing.JLabel LabelESIndex;
    private javax.swing.JLabel LabelESPort;
    protected javax.swing.JSpinner SpinnerESPort;
    protected javax.swing.JTextArea TextAreaJSONSample;
    protected javax.swing.JTextField TextFieldESHost;
    protected javax.swing.JTextField TextFieldESIndex;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
