/*
 * Copyright 2020 Hochikong
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.hochikong.ktmeta.swingui.dialogs;

import com.formdev.flatlaf.intellijthemes.FlatSolarizedLightIJTheme;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author ckhoi
 */
public class TextPreviewDialog extends javax.swing.JDialog {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton BTNCancelAddTextPreview;
    protected javax.swing.JButton BTNClearEditor;
    protected javax.swing.JButton BTNOKAddTextPreview;
    protected javax.swing.JLabel LabelEditorPreview;
    protected javax.swing.JTextArea TextAreaEditor;
    private javax.swing.JLabel LabelEditor;
    private javax.swing.JLabel LabelPreview;
    //</Auto-Generate>
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    //</My-Custom>


    /**
     * Creates new form TextPreviewDialog
     */
    public TextPreviewDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        HideHead();
        this.setLocationRelativeTo(null);
    }
    public TextPreviewDialog(java.awt.Frame parent, boolean modal, Image icon) {
        super(parent, modal);
        initComponents();
        HideHead();
        this.setIconImage(icon);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        FlatSolarizedLightIJTheme.install();

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TextPreviewDialog dialog = new TextPreviewDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNOKAddTextPreview = new javax.swing.JButton();
        BTNCancelAddTextPreview = new javax.swing.JButton();
        LabelEditor = new javax.swing.JLabel();
        LabelPreview = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreaEditor = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        LabelEditorPreview = new javax.swing.JLabel();
        BTNClearEditor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("i18n/Dialogs/TextPreviewDialog_trans"); // NOI18N
        setTitle(bundle.getString("ADD TEXT PREVIEW")); // NOI18N
        setAlwaysOnTop(true);
        setUndecorated(true);

        BTNOKAddTextPreview.setText(bundle.getString("OK")); // NOI18N
        BTNOKAddTextPreview.setFocusable(false);
        BTNOKAddTextPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNOKAddTextPreviewActionPerformed(evt);
            }
        });

        BTNCancelAddTextPreview.setText(bundle.getString("CANCEL")); // NOI18N
        BTNCancelAddTextPreview.setFocusable(false);
        BTNCancelAddTextPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCancelAddTextPreviewActionPerformed(evt);
            }
        });

        LabelEditor.setText(bundle.getString("EDITOR : ")); // NOI18N

        LabelPreview.setText(bundle.getString("PREVIEW : ")); // NOI18N

        TextAreaEditor.setColumns(20);
        TextAreaEditor.setRows(5);
        TextAreaEditor.setText("<html><h1>Preview</h1></html>\n");
        TextAreaEditor.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextAreaEditorCaretUpdate(evt);
            }
        });
        jScrollPane2.setViewportView(TextAreaEditor);

        LabelEditorPreview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jScrollPane1.setViewportView(LabelEditorPreview);

        BTNClearEditor.setText(bundle.getString("CLEAR EDITOR")); // NOI18N
        BTNClearEditor.setFocusable(false);
        BTNClearEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNClearEditorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelEditor)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNClearEditor))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelPreview)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                                .addComponent(BTNOKAddTextPreview)
                                .addGap(18, 18, 18)
                                .addComponent(BTNCancelAddTextPreview))
                            .addComponent(jScrollPane1))
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEditor)
                    .addComponent(LabelPreview))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNClearEditor)
                    .addComponent(BTNOKAddTextPreview)
                    .addComponent(BTNCancelAddTextPreview))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<Auto-Generate>
    private void BTNClearEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNClearEditorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNClearEditorActionPerformed

    private void BTNOKAddTextPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNOKAddTextPreviewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNOKAddTextPreviewActionPerformed

    private void BTNCancelAddTextPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCancelAddTextPreviewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNCancelAddTextPreviewActionPerformed

    private void TextAreaEditorCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextAreaEditorCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_TextAreaEditorCaretUpdate

    //<My-Custom>
    protected void HideHead(){
        // Like IDEA style
        this.getRootPane().setWindowDecorationStyle(JRootPane.FRAME);
    }
    // End of variables declaration//GEN-END:variables
}
