/*
 * Copyright 2020 Hochikong
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distribu    @Override
    public void valueChanged(ListSelectionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
ted on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.hochikong.ktmeta.swingui.dialogs;

import com.formdev.flatlaf.intellijthemes.FlatSolarizedLightIJTheme;
import io.github.hochikong.ktmeta.swingui.essentials.TasksTableModel;

/**
 *
 * @author ckhoi
 */
public class TaskManager extends javax.swing.JDialog {

    /**
     * Creates new form TaskManager
     */
    public TaskManager(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public TaskManager(java.awt.Frame parent, boolean modal, Object[][] Tasks) {
        super(parent, modal);
        this.tasksModel = new TasksTableModel(Tasks);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPaneTM = new javax.swing.JTabbedPane();
        PanelRunningTasks = new javax.swing.JPanel();
        PanelToolBar = new javax.swing.JPanel();
        BTNKillTask = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableTasks = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("i18n/Dialogs/TaskManager_trans"); // NOI18N
        setTitle(bundle.getString("TASK MANAGER")); // NOI18N

        PanelToolBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 136, 199), 2));

        BTNKillTask.setText(bundle.getString("KILL TASK")); // NOI18N
        BTNKillTask.setEnabled(false);
        BTNKillTask.setFocusable(false);
        BTNKillTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNKillTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelToolBarLayout = new javax.swing.GroupLayout(PanelToolBar);
        PanelToolBar.setLayout(PanelToolBarLayout);
        PanelToolBarLayout.setHorizontalGroup(
            PanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelToolBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNKillTask)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelToolBarLayout.setVerticalGroup(
            PanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelToolBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNKillTask)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        TableTasks.setAutoCreateRowSorter(true);
        TableTasks.setModel(this.tasksModel);
        TableTasks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TableTasks.setShowVerticalLines(true);
        jScrollPane1.setViewportView(TableTasks);

        javax.swing.GroupLayout PanelRunningTasksLayout = new javax.swing.GroupLayout(PanelRunningTasks);
        PanelRunningTasks.setLayout(PanelRunningTasksLayout);
        PanelRunningTasksLayout.setHorizontalGroup(
            PanelRunningTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
        );
        PanelRunningTasksLayout.setVerticalGroup(
            PanelRunningTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRunningTasksLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TabbedPaneTM.addTab("Running Tasks", PanelRunningTasks);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPaneTM)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPaneTM)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<Auto-Generate>
    private void BTNKillTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNKillTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNKillTaskActionPerformed
    //</Auto-Generate>
    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        FlatSolarizedLightIJTheme.install();

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaskManager dialog = new TaskManager(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    //<My-Custom>
    protected TasksTableModel tasksModel = new TasksTableModel();
    //</My-Custom>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton BTNKillTask;
    protected javax.swing.JPanel PanelRunningTasks;
    protected javax.swing.JPanel PanelToolBar;
    protected javax.swing.JTabbedPane TabbedPaneTM;
    protected javax.swing.JTable TableTasks;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
