/*
 * Copyright 2020 Hochikong
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.hochikong.ktmeta.swingui.codegen;

import com.formdev.flatlaf.intellijthemes.FlatSolarizedLightIJTheme;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author ckhoi
 */
public class impMetaPreviewManager extends javax.swing.JFrame {

    /**
     * Creates new form PreviewManager
     */
    public impMetaPreviewManager() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public impMetaPreviewManager(String title, Image icon) {
        this.customTitle = title;
        initComponents();
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        LabelForPreview = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BTNAddPreview = new javax.swing.JButton();
        BTNPreviousPage = new javax.swing.JButton();
        BTNNextPage = new javax.swing.JButton();
        BTNDeletePreview = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(this.customTitle);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(97, 800));

        LabelForPreview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelForPreview.setText("<html><h1>Preview</h1></html>");
        jScrollPane1.setViewportView(LabelForPreview);

        getContentPane().add(jScrollPane1);

        jPanel2.setMaximumSize(new java.awt.Dimension(1043, 47));
        jPanel2.setPreferredSize(new java.awt.Dimension(1043, 47));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        BTNAddPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ico/20pix/add.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("i18n/Frames/MetaPreviewManager_trans"); // NOI18N
        BTNAddPreview.setToolTipText(bundle.getString("ADD PREVIEW")); // NOI18N
        BTNAddPreview.setFocusable(false);
        BTNAddPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAddPreviewActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(BTNAddPreview, gridBagConstraints);

        BTNPreviousPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ico/20pix/previous.png"))); // NOI18N
        BTNPreviousPage.setToolTipText(bundle.getString("PREVIOUS PREVIEW")); // NOI18N
        BTNPreviousPage.setFocusable(false);
        BTNPreviousPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPreviousPageActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(BTNPreviousPage, gridBagConstraints);

        BTNNextPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ico/20pix/next.png"))); // NOI18N
        BTNNextPage.setToolTipText(bundle.getString("NEXT PREVIEW")); // NOI18N
        BTNNextPage.setFocusable(false);
        BTNNextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNNextPageActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(BTNNextPage, gridBagConstraints);

        BTNDeletePreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ico/20pix/material-delete.png"))); // NOI18N
        BTNDeletePreview.setToolTipText(bundle.getString("DELETE PREVIEW")); // NOI18N
        BTNDeletePreview.setFocusable(false);
        BTNDeletePreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDeletePreviewActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(BTNDeletePreview, gridBagConstraints);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<Auto-Generate>
    private void BTNAddPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAddPreviewActionPerformed
        impBTNAddPreviewActionPerformed(evt);
//        int whatPreviewYouChoose = JOptionPane.showOptionDialog(
//                this.LabelForPreview, 
//                tipForOptionPane, 
//                titleForOptionPane,
//                JOptionPane.YES_NO_CANCEL_OPTION, 
//                JOptionPane.QUESTION_MESSAGE,
//                null,
//                options,
//                options[0]
//                );
//        System.out.println(whatPreviewYouChoose);
    }//GEN-LAST:event_BTNAddPreviewActionPerformed

    private void BTNPreviousPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPreviousPageActionPerformed
        impBTNPreviousPageActionPerformed(evt);
    }//GEN-LAST:event_BTNPreviousPageActionPerformed

    private void BTNNextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNNextPageActionPerformed
        impBTNNextPageActionPerformed(evt);
    }//GEN-LAST:event_BTNNextPageActionPerformed

    private void BTNDeletePreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDeletePreviewActionPerformed
        impBTNDeletePreviewActionPerformed(evt);
    }//GEN-LAST:event_BTNDeletePreviewActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        impformComponentResized(evt);
    }//GEN-LAST:event_formComponentResized
    //</Auto-Generate>
    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        FlatSolarizedLightIJTheme.install();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new impMetaPreviewManager().setVisible(true);
            }
        });
    }
    
    //<My-Custom>
    protected String customTitle = java.util.ResourceBundle.getBundle("i18n/Frames/MetaPreviewManager_trans").getString("PREVIEW MANANGER -- ENLARGE PREVIEW : 1/1 PAGE");
    private final Object[] options = {java.util.ResourceBundle.getBundle("i18n/Frames/MetaPreviewManager_trans").getString("A PICTURE"), java.util.ResourceBundle.getBundle("i18n/Frames/MetaPreviewManager_trans").getString("A TEXT")};
    private final String tipForOptionPane = java.util.ResourceBundle.getBundle("i18n/Frames/MetaPreviewManager_trans").getString("CHOOSE WHAT YOU WANT TO ADD AS PREVIEW : ");
    private final String titleForOptionPane = java.util.ResourceBundle.getBundle("i18n/Frames/MetaPreviewManager_trans").getString("ADD PREVIEW ? ");
    
    // Text or base64 code:
    protected String previewContent;

    protected void setPreview(String content) {
        if (content != null) {
            this.LabelForPreview.setText(content);
        }
    }

    protected void setPreview(ImageIcon image) {
        if (image != null) {
            this.LabelForPreview.setIcon(image);
        }
    }
    //</My-Custom>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton BTNAddPreview;
    protected javax.swing.JButton BTNDeletePreview;
    protected javax.swing.JButton BTNNextPage;
    protected javax.swing.JButton BTNPreviousPage;
    protected javax.swing.JLabel LabelForPreview;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    //<Auto-Generate-Result>
    protected void impBTNAddPreviewActionPerformed(java.awt.event.ActionEvent evt){}
    protected void impBTNPreviousPageActionPerformed(java.awt.event.ActionEvent evt){}
    protected void impBTNNextPageActionPerformed(java.awt.event.ActionEvent evt){}
    protected void impBTNDeletePreviewActionPerformed(java.awt.event.ActionEvent evt){}
    protected void impformComponentResized(java.awt.event.ComponentEvent evt){}
    //</Auto-Generate-Result>
}
