/*
 * Copyright 2020 Hochikong
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.hochikong.ktmeta.swingui.essentials;

import javax.swing.table.TableModel;
import java.nio.charset.StandardCharsets;
import java.util.Random;

/**
 *
 * @author ckhoi
 */
public class SimpleResultPanelContainer extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public SimpleResultPanelContainer() {
        initComponents();
    }

    public SimpleResultPanelContainer(TableModel model) {
        this.injectModel = model;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelResultToolbar = new javax.swing.JPanel();
        BTNGotoFirstPage = new javax.swing.JButton();
        BTNGotoPreviousPage = new javax.swing.JButton();
        SpinnerMaxRows = new javax.swing.JSpinner();
        LabelResultRows = new javax.swing.JLabel();
        BTNGotoNextPage = new javax.swing.JButton();
        BTNGotoLastPage = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        BTNRefresh = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        BTNDeleteRow = new javax.swing.JButton();
        BTNAddRow = new javax.swing.JButton();
        SRPScrollPane = new javax.swing.JScrollPane();
        TableResult = new javax.swing.JTable();

        PanelResultToolbar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 131, 201)));

        BTNGotoFirstPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ico/16pix/angle-double-left.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("i18n/OtherComponents/SimpleResultPanelContainer_trans"); // NOI18N
        BTNGotoFirstPage.setToolTipText(bundle.getString("FIRST PAGE")); // NOI18N
        BTNGotoFirstPage.setFocusable(false);
        BTNGotoFirstPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGotoFirstPageActionPerformed(evt);
            }
        });

        BTNGotoPreviousPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ico/16pix/angle-left.png"))); // NOI18N
        BTNGotoPreviousPage.setToolTipText(bundle.getString("PREVIOUS PAGE")); // NOI18N
        BTNGotoPreviousPage.setFocusable(false);
        BTNGotoPreviousPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGotoPreviousPageActionPerformed(evt);
            }
        });

        SpinnerMaxRows.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinnerMaxRowsStateChanged(evt);
            }
        });

        LabelResultRows.setText("0-20 of 100 results");
        LabelResultRows.setToolTipText("");

        BTNGotoNextPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ico/16pix/angle-right.png"))); // NOI18N
        BTNGotoNextPage.setToolTipText(bundle.getString("NEXT PAGE")); // NOI18N
        BTNGotoNextPage.setFocusable(false);
        BTNGotoNextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGotoNextPageActionPerformed(evt);
            }
        });

        BTNGotoLastPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ico/16pix/angle-double-right.png"))); // NOI18N
        BTNGotoLastPage.setToolTipText(bundle.getString("LAST PAGE")); // NOI18N
        BTNGotoLastPage.setFocusable(false);
        BTNGotoLastPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGotoLastPageActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        BTNRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ico/16pix/sync-alt.png"))); // NOI18N
        BTNRefresh.setToolTipText(bundle.getString("REFRESH")); // NOI18N
        BTNRefresh.setFocusable(false);
        BTNRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRefreshActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        BTNDeleteRow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ico/16pix/delete.png"))); // NOI18N
        BTNDeleteRow.setToolTipText(bundle.getString("DELETE SELECTED METADATA")); // NOI18N
        BTNDeleteRow.setFocusable(false);
        BTNDeleteRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDeleteRowActionPerformed(evt);
            }
        });

        BTNAddRow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ico/16pix/add.png"))); // NOI18N
        BTNAddRow.setToolTipText(bundle.getString("ADD NEW METADATA")); // NOI18N
        BTNAddRow.setFocusable(false);
        BTNAddRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAddRowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelResultToolbarLayout = new javax.swing.GroupLayout(PanelResultToolbar);
        PanelResultToolbar.setLayout(PanelResultToolbarLayout);
        PanelResultToolbarLayout.setHorizontalGroup(
            PanelResultToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelResultToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNGotoFirstPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNGotoPreviousPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpinnerMaxRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelResultRows)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNGotoNextPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNGotoLastPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNDeleteRow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNAddRow)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelResultToolbarLayout.setVerticalGroup(
            PanelResultToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelResultToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelResultToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTNDeleteRow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelResultToolbarLayout.createSequentialGroup()
                        .addGroup(PanelResultToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BTNRefresh)
                            .addGroup(PanelResultToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BTNGotoLastPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTNGotoNextPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTNGotoFirstPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTNGotoPreviousPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SpinnerMaxRows, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(LabelResultRows, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator3)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(BTNAddRow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        TableResult.setAutoCreateRowSorter(true);
        TableResult.setModel(this.injectModel);
        TableResult.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TableResult.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        SRPScrollPane.setViewportView(TableResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelResultToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SRPScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelResultToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SRPScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    //<Auto-Generate>
    private void BTNGotoFirstPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGotoFirstPageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNGotoFirstPageActionPerformed

    private void BTNGotoPreviousPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGotoPreviousPageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNGotoPreviousPageActionPerformed

    private void SpinnerMaxRowsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinnerMaxRowsStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_SpinnerMaxRowsStateChanged

    private void BTNGotoNextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGotoNextPageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNGotoNextPageActionPerformed

    private void BTNGotoLastPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGotoLastPageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNGotoLastPageActionPerformed

    private void BTNRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRefreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNRefreshActionPerformed

    private void BTNDeleteRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDeleteRowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNDeleteRowActionPerformed

    private void BTNAddRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAddRowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNAddRowActionPerformed
    //</Auto-Generate>

    private TableModel injectModel = new javax.swing.table.DefaultTableModel(
            new Object[][]{
                {getRandomString(), getRandomString()},
                {getRandomString(), getRandomString()}
            },
            new String[]{
                "Result : ", "Match on : "
            }
    );

    private String getRandomString() {
        byte[] array = new byte[7]; // length is bounded by 7
        new Random().nextBytes(array);
        return new String(array, StandardCharsets.UTF_8);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton BTNAddRow;
    protected javax.swing.JButton BTNDeleteRow;
    protected javax.swing.JButton BTNGotoFirstPage;
    protected javax.swing.JButton BTNGotoLastPage;
    protected javax.swing.JButton BTNGotoNextPage;
    protected javax.swing.JButton BTNGotoPreviousPage;
    protected javax.swing.JButton BTNRefresh;
    protected javax.swing.JLabel LabelResultRows;
    protected javax.swing.JPanel PanelResultToolbar;
    private javax.swing.JScrollPane SRPScrollPane;
    protected javax.swing.JSpinner SpinnerMaxRows;
    protected javax.swing.JTable TableResult;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
