/*
 * Copyright 2020 Hochikong
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.hochikong.ktmeta.swingui;

import javax.swing.ImageIcon;
import java.awt.image.BufferedImage;
import com.formdev.flatlaf.intellijthemes.*;
import io.github.hochikong.ktmeta.swingui.essentials.SimpleResultPanelContainer;
import io.github.hochikong.ktmeta.swingui.essentials.VerticalTabComp;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import java.util.HashMap;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.JTree;
import javax.swing.table.TableModel;

/**
 *
 * @author ckhoi
 */
public class KtmetaMainFrameDesign extends javax.swing.JFrame {

    /**
     * Creates new form KtmetaJFrame
     */
    public KtmetaMainFrameDesign() {
        // UIManager.getLookAndFeelDefaults().put("defaultFont", new Font("GenYoMin TW B", Font.PLAIN, 14));
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIcon();
        // this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopupMenuAbstract = new javax.swing.JPopupMenu();
        PMAbstractCopyAll = new javax.swing.JMenuItem();
        PMAbstractCopySelected = new javax.swing.JMenuItem();
        PopupMenuTags = new javax.swing.JPopupMenu();
        PMTagsAddCustom = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        PMTagsCopyAll = new javax.swing.JMenuItem();
        PMTagsCopySelected = new javax.swing.JMenuItem();
        PopupMenuPreview = new javax.swing.JPopupMenu();
        PMViewEnlarge = new javax.swing.JMenuItem();
        PopupMenuDatabasesTree = new javax.swing.JPopupMenu();
        PMRenameDatabase = new javax.swing.JMenuItem();
        PMDBPropertiesEdit = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        PMExportDatabaseData = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        PMRemoveDatabase = new javax.swing.JMenuItem();
        PopupMenuIndicesTree = new javax.swing.JPopupMenu();
        PMRenameIndices = new javax.swing.JMenuItem();
        PMIndexPropertiesEdit = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        PMExportJSON = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        PMRemoveIndex = new javax.swing.JMenuItem();
        PopupMenuMetaLibsTree = new javax.swing.JPopupMenu();
        PMRenameMetaLib = new javax.swing.JMenuItem();
        PMMetaLibProperties = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        PMImportDataToDB = new javax.swing.JMenuItem();
        PMSyncToES = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        PMRemoveMetaLib = new javax.swing.JMenuItem();
        PopupMenuMetadataDetails = new javax.swing.JPopupMenu();
        PMDetailsExportToFile = new javax.swing.JMenuItem();
        ButtonGroupOnAttr = new javax.swing.ButtonGroup();
        ButtonGroupOnWhere = new javax.swing.ButtonGroup();
        ToolBarPanel = new javax.swing.JPanel();
        MainToolBar = new javax.swing.JToolBar();
        BTNAddDatabase = new javax.swing.JButton();
        BTNAddESIndex = new javax.swing.JButton();
        BTNAddMetaLib = new javax.swing.JButton();
        jSeparator14 = new javax.swing.JToolBar.Separator();
        MainSplitPane = new javax.swing.JSplitPane();
        SplitPaneSubLeft = new javax.swing.JPanel();
        SplitPaneSubVTLeft = new javax.swing.JSplitPane();
        SubLeftUpTab = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        DefaultMutableTreeNode mtlb = new DefaultMutableTreeNode("Metadata Libs");
        TreeMetadataLibs = new javax.swing.JTree(mtlb);
        SubLeftDown = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        DefaultMutableTreeNode dbms = new DefaultMutableTreeNode("DBMS");
        DefaultMutableTreeNode sqlite = new DefaultMutableTreeNode("SQLite");
        DefaultMutableTreeNode postgresql = new DefaultMutableTreeNode("PostgreSQL");
        dbms.add(sqlite);
        dbms.add(postgresql);
        TreeDatabases = new javax.swing.JTree(dbms);
        jScrollPane2 = new javax.swing.JScrollPane();
        DefaultMutableTreeNode esind = new DefaultMutableTreeNode("ElasticSearch Indices");
        TreeIndices = new javax.swing.JTree(esind);
        SplitPaneSubRight = new javax.swing.JSplitPane();
        PanelSplitCenter = new javax.swing.JPanel();
        SplitPaneVTGeneral = new javax.swing.JSplitPane();
        TabbedPaneQueryResult = new javax.swing.JTabbedPane();
        PanelResultTemplate = new javax.swing.JPanel();
        PanelResultToolbar = new javax.swing.JPanel();
        BTNGotoFirstPage = new javax.swing.JButton();
        BTNGotoPreviousPage = new javax.swing.JButton();
        SpinnerMaxRows = new javax.swing.JSpinner();
        LabelResultRows = new javax.swing.JLabel();
        BTNGotoNextPage = new javax.swing.JButton();
        BTNGotoLastPage = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        BTNRefresh = new javax.swing.JButton();
        SRPScrollPane = new javax.swing.JScrollPane();
        TableResult = new javax.swing.JTable();
        PanelQuery = new javax.swing.JTabbedPane();
        PanelQuickQuery = new javax.swing.JPanel();
        LabelQQueryOnMetaLib = new javax.swing.JLabel();
        ComboBoxQQueryAvailableMetaLibs = new javax.swing.JComboBox<>();
        CheckBoxQQueryCreateNewTab = new javax.swing.JCheckBox();
        LabelQQuerySearch = new javax.swing.JLabel();
        TextFieldQQuerySearch = new javax.swing.JTextField();
        BTNQuickQuerySearch = new javax.swing.JButton();
        BTNQQueryHelper = new javax.swing.JButton();
        CheckBoxQQueryOnDB = new javax.swing.JCheckBox();
        CheckBoxQQueryOnES = new javax.swing.JCheckBox();
        PanelInfoOutput = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        TabbedPaneSplitRight = new javax.swing.JTabbedPane();
        PanelRightPreview = new javax.swing.JPanel();
        LabelRightAbstract = new javax.swing.JLabel();
        LabelRightTags = new javax.swing.JLabel();
        LabelRightPreview = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        RightTextPaneAbstract = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        RightTextPaneTags = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        RightPreviewLabel = new javax.swing.JLabel();
        BTNRightPreviewEnlargeShotcut = new javax.swing.JButton();
        RightDetailsPane = new javax.swing.JPanel();
        RightLabelMetadataDoc = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        RightTextPaneMetaDoc = new javax.swing.JTextPane();
        BottomPanel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        MainMenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        MenuItemNewMetaLib = new javax.swing.JMenuItem();
        MenuItemScanMetas = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MenuItemAddDatabase = new javax.swing.JMenuItem();
        MenuItemAddIndex = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        MenuItemSettings = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        MenuItemExit = new javax.swing.JMenuItem();
        EditMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        ToolsMenu = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();
        MenuItemAbout = new javax.swing.JMenuItem();

        PMAbstractCopyAll.setText("Copy All");
        PopupMenuAbstract.add(PMAbstractCopyAll);

        PMAbstractCopySelected.setText("Copy Selected");
        PopupMenuAbstract.add(PMAbstractCopySelected);

        PMTagsAddCustom.setText("Add Custom Tags");
        PopupMenuTags.add(PMTagsAddCustom);
        PopupMenuTags.add(jSeparator8);

        PMTagsCopyAll.setText("Copy All");
        PopupMenuTags.add(PMTagsCopyAll);

        PMTagsCopySelected.setText("Copy Selected");
        PopupMenuTags.add(PMTagsCopySelected);

        PMViewEnlarge.setText("Enlarge Preview");
        PopupMenuPreview.add(PMViewEnlarge);

        PMRenameDatabase.setText("Rename");
        PopupMenuDatabasesTree.add(PMRenameDatabase);

        PMDBPropertiesEdit.setText("Properties");
        PopupMenuDatabasesTree.add(PMDBPropertiesEdit);
        PopupMenuDatabasesTree.add(jSeparator6);

        PMExportDatabaseData.setText("Export Data to Files");
        PopupMenuDatabasesTree.add(PMExportDatabaseData);
        PopupMenuDatabasesTree.add(jSeparator7);

        PMRemoveDatabase.setText("Remove");
        PopupMenuDatabasesTree.add(PMRemoveDatabase);

        PMRenameIndices.setText("Rename");
        PopupMenuIndicesTree.add(PMRenameIndices);

        PMIndexPropertiesEdit.setText("Properties");
        PopupMenuIndicesTree.add(PMIndexPropertiesEdit);
        PopupMenuIndicesTree.add(jSeparator9);

        PMExportJSON.setText("Export JSON Documents");
        PopupMenuIndicesTree.add(PMExportJSON);
        PopupMenuIndicesTree.add(jSeparator10);

        PMRemoveIndex.setText("Remove");
        PopupMenuIndicesTree.add(PMRemoveIndex);

        PMRenameMetaLib.setText("Rename");
        PopupMenuMetaLibsTree.add(PMRenameMetaLib);

        PMMetaLibProperties.setText("Properties");
        PopupMenuMetaLibsTree.add(PMMetaLibProperties);
        PopupMenuMetaLibsTree.add(jSeparator12);

        PMImportDataToDB.setText("Import Metadata to Database");
        PopupMenuMetaLibsTree.add(PMImportDataToDB);

        PMSyncToES.setText("Sync Data to ElasticSearch");
        PopupMenuMetaLibsTree.add(PMSyncToES);
        PopupMenuMetaLibsTree.add(jSeparator13);

        PMRemoveMetaLib.setText("Remove");
        PopupMenuMetaLibsTree.add(PMRemoveMetaLib);

        PMDetailsExportToFile.setText("Export To File");
        PopupMenuMetadataDetails.add(PMDetailsExportToFile);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ktmeta");
        setIconImages(null);
        setName("MainFrame"); // NOI18N
        setSize(new java.awt.Dimension(1920, 1080));

        ToolBarPanel.setMaximumSize(new java.awt.Dimension(159, 35));
        ToolBarPanel.setMinimumSize(new java.awt.Dimension(159, 35));
        ToolBarPanel.setPreferredSize(new java.awt.Dimension(159, 35));

        MainToolBar.setFloatable(false);
        MainToolBar.setRollover(true);

        BTNAddDatabase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ico/20pix/database.png"))); // NOI18N
        BTNAddDatabase.setToolTipText("Add Database");
        BTNAddDatabase.setFocusable(false);
        BTNAddDatabase.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTNAddDatabase.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MainToolBar.add(BTNAddDatabase);

        BTNAddESIndex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ico/20pix/es.png"))); // NOI18N
        BTNAddESIndex.setToolTipText("Add Metadata Library");
        BTNAddESIndex.setFocusable(false);
        BTNAddESIndex.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTNAddESIndex.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MainToolBar.add(BTNAddESIndex);

        BTNAddMetaLib.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ico/20pix/metalib.png"))); // NOI18N
        BTNAddMetaLib.setToolTipText("Add Metadata Library");
        BTNAddMetaLib.setFocusable(false);
        BTNAddMetaLib.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTNAddMetaLib.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MainToolBar.add(BTNAddMetaLib);

        jSeparator14.setForeground(new java.awt.Color(204, 204, 204));
        MainToolBar.add(jSeparator14);

        javax.swing.GroupLayout ToolBarPanelLayout = new javax.swing.GroupLayout(ToolBarPanel);
        ToolBarPanel.setLayout(ToolBarPanelLayout);
        ToolBarPanelLayout.setHorizontalGroup(
            ToolBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ToolBarPanelLayout.setVerticalGroup(
            ToolBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ToolBarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MainToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        SplitPaneSubLeft.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        SplitPaneSubLeft.setPreferredSize(new java.awt.Dimension(250, 981));

        SplitPaneSubVTLeft.setDividerLocation(450);
        SplitPaneSubVTLeft.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        SplitPaneSubVTLeft.setPreferredSize(new java.awt.Dimension(100, 206));

        jScrollPane3.setViewportView(TreeMetadataLibs);

        SubLeftUpTab.addTab("Metadata Libraries", jScrollPane3);

        SplitPaneSubVTLeft.setTopComponent(SubLeftUpTab);

        jScrollPane1.setViewportView(TreeDatabases);

        SubLeftDown.addTab("Databases", jScrollPane1);

        jScrollPane2.setViewportView(TreeIndices);

        SubLeftDown.addTab("ES Indices", jScrollPane2);

        SplitPaneSubVTLeft.setBottomComponent(SubLeftDown);

        javax.swing.GroupLayout SplitPaneSubLeftLayout = new javax.swing.GroupLayout(SplitPaneSubLeft);
        SplitPaneSubLeft.setLayout(SplitPaneSubLeftLayout);
        SplitPaneSubLeftLayout.setHorizontalGroup(
            SplitPaneSubLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPaneSubVTLeft, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );
        SplitPaneSubLeftLayout.setVerticalGroup(
            SplitPaneSubLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPaneSubVTLeft, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
        );

        MainSplitPane.setLeftComponent(SplitPaneSubLeft);

        PanelSplitCenter.setMinimumSize(new java.awt.Dimension(100, 100));
        PanelSplitCenter.setPreferredSize(new java.awt.Dimension(900, 700));

        SplitPaneVTGeneral.setDividerLocation(580);
        SplitPaneVTGeneral.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        SplitPaneVTGeneral.setOneTouchExpandable(true);
        SplitPaneVTGeneral.setPreferredSize(new java.awt.Dimension(900, 856));

        TabbedPaneQueryResult.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TabbedPaneQueryResult.setPreferredSize(new java.awt.Dimension(900, 650));

        PanelResultToolbar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 131, 201)));

        BTNGotoFirstPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ico/16pix/angle-double-left.png"))); // NOI18N
        BTNGotoFirstPage.setToolTipText("First page");
        BTNGotoFirstPage.setFocusable(false);

        BTNGotoPreviousPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ico/16pix/angle-left.png"))); // NOI18N
        BTNGotoPreviousPage.setToolTipText("Previous page");
        BTNGotoPreviousPage.setFocusable(false);

        LabelResultRows.setText("0-20 of 100 results");
        LabelResultRows.setToolTipText("");

        BTNGotoNextPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ico/16pix/angle-right.png"))); // NOI18N
        BTNGotoNextPage.setToolTipText("Next page");
        BTNGotoNextPage.setFocusable(false);

        BTNGotoLastPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ico/16pix/angle-double-right.png"))); // NOI18N
        BTNGotoLastPage.setToolTipText("Last page");
        BTNGotoLastPage.setFocusable(false);

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        BTNRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ico/16pix/sync-alt.png"))); // NOI18N
        BTNRefresh.setToolTipText("Refresh");
        BTNRefresh.setFocusable(false);

        javax.swing.GroupLayout PanelResultToolbarLayout = new javax.swing.GroupLayout(PanelResultToolbar);
        PanelResultToolbar.setLayout(PanelResultToolbarLayout);
        PanelResultToolbarLayout.setHorizontalGroup(
            PanelResultToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelResultToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNGotoFirstPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNGotoPreviousPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpinnerMaxRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelResultRows)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNGotoNextPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNGotoLastPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNRefresh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelResultToolbarLayout.setVerticalGroup(
            PanelResultToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelResultToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelResultToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTNRefresh)
                    .addGroup(PanelResultToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BTNGotoLastPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNGotoNextPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNGotoFirstPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNGotoPreviousPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SpinnerMaxRows, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(LabelResultRows, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TableResult.setModel(buildSearchResultModel());
        TableResult.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TableResult.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        SRPScrollPane.setViewportView(TableResult);

        javax.swing.GroupLayout PanelResultTemplateLayout = new javax.swing.GroupLayout(PanelResultTemplate);
        PanelResultTemplate.setLayout(PanelResultTemplateLayout);
        PanelResultTemplateLayout.setHorizontalGroup(
            PanelResultTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelResultToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SRPScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
        );
        PanelResultTemplateLayout.setVerticalGroup(
            PanelResultTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelResultTemplateLayout.createSequentialGroup()
                .addComponent(PanelResultToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SRPScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
        );

        TabbedPaneQueryResult.addTab("Search result template", PanelResultTemplate);

        SplitPaneVTGeneral.setLeftComponent(TabbedPaneQueryResult);

        PanelQuery.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelQuery.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        PanelQuery.setMinimumSize(new java.awt.Dimension(104, 40));
        PanelQuery.setPreferredSize(new java.awt.Dimension(1280, 200));

        LabelQQueryOnMetaLib.setText("On Metadata Library : ");

        ComboBoxQQueryAvailableMetaLibs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CheckBoxQQueryCreateNewTab.setText("Create New Tab");

        LabelQQuerySearch.setText("Search : ");

        TextFieldQQuerySearch.setForeground(new java.awt.Color(204, 204, 204));
        TextFieldQQuerySearch.setText("Something");

        BTNQuickQuerySearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ico/20pix/search.png"))); // NOI18N
        BTNQuickQuerySearch.setFocusable(false);

        BTNQQueryHelper.setText("?");

        ButtonGroupOnWhere.add(CheckBoxQQueryOnDB);
        CheckBoxQQueryOnDB.setText("On Database");

        ButtonGroupOnWhere.add(CheckBoxQQueryOnES);
        CheckBoxQQueryOnES.setText("On ElasticSearch");

        javax.swing.GroupLayout PanelQuickQueryLayout = new javax.swing.GroupLayout(PanelQuickQuery);
        PanelQuickQuery.setLayout(PanelQuickQueryLayout);
        PanelQuickQueryLayout.setHorizontalGroup(
            PanelQuickQueryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelQuickQueryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelQuickQueryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelQuickQueryLayout.createSequentialGroup()
                        .addComponent(LabelQQueryOnMetaLib)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBoxQQueryAvailableMetaLibs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CheckBoxQQueryCreateNewTab))
                    .addGroup(PanelQuickQueryLayout.createSequentialGroup()
                        .addComponent(LabelQQuerySearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldQQuerySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNQuickQuerySearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNQQueryHelper))
                    .addComponent(CheckBoxQQueryOnES)
                    .addComponent(CheckBoxQQueryOnDB))
                .addContainerGap(399, Short.MAX_VALUE))
        );
        PanelQuickQueryLayout.setVerticalGroup(
            PanelQuickQueryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelQuickQueryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelQuickQueryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxQQueryAvailableMetaLibs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelQQueryOnMetaLib)
                    .addComponent(CheckBoxQQueryCreateNewTab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelQuickQueryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelQuickQueryLayout.createSequentialGroup()
                        .addGroup(PanelQuickQueryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelQQuerySearch)
                            .addComponent(TextFieldQQuerySearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNQuickQuerySearch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CheckBoxQQueryOnDB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CheckBoxQQueryOnES))
                    .addComponent(BTNQQueryHelper))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        PanelQuery.addTab("Full-Text Search", PanelQuickQuery);

        PanelInfoOutput.setPreferredSize(new java.awt.Dimension(896, 686));

        javax.swing.GroupLayout PanelInfoOutputLayout = new javax.swing.GroupLayout(PanelInfoOutput);
        PanelInfoOutput.setLayout(PanelInfoOutputLayout);
        PanelInfoOutputLayout.setHorizontalGroup(
            PanelInfoOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 896, Short.MAX_VALUE)
        );
        PanelInfoOutputLayout.setVerticalGroup(
            PanelInfoOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );

        PanelQuery.addTab("Info", PanelInfoOutput);

        jButton1.setText("Test");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(800, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        PanelQuery.addTab("tab3", jPanel1);

        SplitPaneVTGeneral.setRightComponent(PanelQuery);

        javax.swing.GroupLayout PanelSplitCenterLayout = new javax.swing.GroupLayout(PanelSplitCenter);
        PanelSplitCenter.setLayout(PanelSplitCenterLayout);
        PanelSplitCenterLayout.setHorizontalGroup(
            PanelSplitCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPaneVTGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelSplitCenterLayout.setVerticalGroup(
            PanelSplitCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSplitCenterLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(SplitPaneVTGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE))
        );

        SplitPaneSubRight.setLeftComponent(PanelSplitCenter);

        TabbedPaneSplitRight.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TabbedPaneSplitRight.setTabPlacement(javax.swing.JTabbedPane.RIGHT);

        LabelRightAbstract.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        LabelRightAbstract.setText("Abstract : ");

        LabelRightTags.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        LabelRightTags.setText("Tags : ");

        LabelRightPreview.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        LabelRightPreview.setText("1st Preview : ");

        RightTextPaneAbstract.setText("No Abstract");
        RightTextPaneAbstract.setToolTipText("You can copy them");
        jScrollPane4.setViewportView(RightTextPaneAbstract);

        RightTextPaneTags.setText("No Tags");
        RightTextPaneTags.setToolTipText("Right click to add custom tags");
        jScrollPane5.setViewportView(RightTextPaneTags);

        RightPreviewLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RightPreviewLabel.setText("<html><h1>Preview</h1><br>Empty</html>");
        RightPreviewLabel.setToolTipText("Right click to enlarge preview");
        jScrollPane6.setViewportView(RightPreviewLabel);

        BTNRightPreviewEnlargeShotcut.setText("Zoom In / More");
        BTNRightPreviewEnlargeShotcut.setFocusable(false);

        javax.swing.GroupLayout PanelRightPreviewLayout = new javax.swing.GroupLayout(PanelRightPreview);
        PanelRightPreview.setLayout(PanelRightPreviewLayout);
        PanelRightPreviewLayout.setHorizontalGroup(
            PanelRightPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRightPreviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRightPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelRightPreviewLayout.createSequentialGroup()
                        .addGroup(PanelRightPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelRightAbstract, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelRightTags, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 208, Short.MAX_VALUE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelRightPreviewLayout.createSequentialGroup()
                        .addComponent(LabelRightPreview)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNRightPreviewEnlargeShotcut)))
                .addContainerGap())
        );
        PanelRightPreviewLayout.setVerticalGroup(
            PanelRightPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRightPreviewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelRightAbstract)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelRightTags)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelRightPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelRightPreview)
                    .addComponent(BTNRightPreviewEnlargeShotcut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPaneSplitRight.addTab("Preview", PanelRightPreview);
        rightVerticalTabLabels.put("PreviewVT", new JLabel("Preview"));
        rightVerticalTabLabels.get("PreviewVT").setPreferredSize(new Dimension(12, 60));
        rightVerticalTabLabels.get("PreviewVT").setVerticalAlignment(SwingConstants.CENTER);
        rightVerticalTabLabels.get("PreviewVT").setHorizontalAlignment(SwingConstants.CENTER);
        rightVerticalTabLabels.get("PreviewVT").setUI(new VerticalTabComp(true));
        TabbedPaneSplitRight.setTabComponentAt(0, rightVerticalTabLabels.get("PreviewVT"));

        RightLabelMetadataDoc.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        RightLabelMetadataDoc.setText("Metadata document : ");

        RightTextPaneMetaDoc.setEditable(false);
        RightTextPaneMetaDoc.setText("No Metadata");
        jScrollPane7.setViewportView(RightTextPaneMetaDoc);

        javax.swing.GroupLayout RightDetailsPaneLayout = new javax.swing.GroupLayout(RightDetailsPane);
        RightDetailsPane.setLayout(RightDetailsPaneLayout);
        RightDetailsPaneLayout.setHorizontalGroup(
            RightDetailsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightDetailsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RightDetailsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RightDetailsPaneLayout.createSequentialGroup()
                        .addComponent(RightLabelMetadataDoc)
                        .addGap(0, 104, Short.MAX_VALUE))
                    .addComponent(jScrollPane7))
                .addContainerGap())
        );
        RightDetailsPaneLayout.setVerticalGroup(
            RightDetailsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightDetailsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RightLabelMetadataDoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPaneSplitRight.addTab("Details", RightDetailsPane);
        rightVerticalTabLabels.put("DetailsVT", new JLabel("Details"));
        rightVerticalTabLabels.get("DetailsVT").setPreferredSize(new Dimension(12, 60));
        rightVerticalTabLabels.get("DetailsVT").setVerticalAlignment(SwingConstants.CENTER);
        rightVerticalTabLabels.get("DetailsVT").setHorizontalAlignment(SwingConstants.CENTER);
        rightVerticalTabLabels.get("DetailsVT").setUI(new VerticalTabComp(true));
        TabbedPaneSplitRight.setTabComponentAt(1, rightVerticalTabLabels.get("DetailsVT"));

        SplitPaneSubRight.setRightComponent(TabbedPaneSplitRight);

        MainSplitPane.setRightComponent(SplitPaneSubRight);

        BottomPanel.setPreferredSize(new java.awt.Dimension(100, 35));
        BottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton3.setText("Running Tasks");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusable(false);
        BottomPanel.add(jButton3);

        FileMenu.setText("File");

        MenuItemNewMetaLib.setText("Add New Metadata Lib");
        FileMenu.add(MenuItemNewMetaLib);

        MenuItemScanMetas.setIcon(new ImageIcon(new BufferedImage(20, 20, BufferedImage.TYPE_INT_ARGB)));
        MenuItemScanMetas.setText("Scan Metadata");
        FileMenu.add(MenuItemScanMetas);
        FileMenu.add(jSeparator1);

        MenuItemAddDatabase.setIcon(new ImageIcon(new BufferedImage(20, 20, BufferedImage.TYPE_INT_ARGB)));
        MenuItemAddDatabase.setText("Add New Database");
        FileMenu.add(MenuItemAddDatabase);

        MenuItemAddIndex.setIcon(new ImageIcon(new BufferedImage(20, 20, BufferedImage.TYPE_INT_ARGB)));
        MenuItemAddIndex.setText("Add New ES Index");
        FileMenu.add(MenuItemAddIndex);
        FileMenu.add(jSeparator4);

        MenuItemSettings.setText("Settings");
        FileMenu.add(MenuItemSettings);
        FileMenu.add(jSeparator5);

        MenuItemExit.setText("Exit");
        FileMenu.add(MenuItemExit);

        MainMenuBar.add(FileMenu);

        EditMenu.setText("Edit");

        jMenuItem2.setText("Find");
        EditMenu.add(jMenuItem2);

        MainMenuBar.add(EditMenu);

        ToolsMenu.setText("Tools");

        jMenuItem4.setText("Plugins");
        ToolsMenu.add(jMenuItem4);
        ToolsMenu.add(jSeparator2);

        jMenuItem1.setIcon(new ImageIcon(new BufferedImage(20, 20, BufferedImage.TYPE_INT_ARGB)));
        jMenuItem1.setText("ElasticSearch");
        ToolsMenu.add(jMenuItem1);

        MainMenuBar.add(ToolsMenu);

        HelpMenu.setText("Help");

        MenuItemAbout.setIcon(new ImageIcon(new BufferedImage(20, 20, BufferedImage.TYPE_INT_ARGB)));
        MenuItemAbout.setText("About");
        HelpMenu.add(MenuItemAbout);

        MainMenuBar.add(HelpMenu);

        setJMenuBar(MainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainSplitPane)
            .addComponent(ToolBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1556, Short.MAX_VALUE)
            .addComponent(BottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ToolBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MainSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(BottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SimpleResultPanelContainer tmp = new SimpleResultPanelContainer(buildSearchResultModel());
        this.TabbedPaneQueryResult.addTab("TEST", tmp);
    }//GEN-LAST:event_jButton1ActionPerformed

    // *************************************************************************
    // my custom codes
    // Used by TabbedPaneSplitRight to keep the reference of JLabels.
    private int testIndex = 0;
    
    protected HashMap<String, JLabel> rightVerticalTabLabels = new HashMap<>();

    // Used by TreeDatabases, TreeIndices and TreeMetadataLibs to store which rows are selected.
    protected int[] databaseTreeSelectionRows;
    protected int[] indicesTreeSelectionRows;
    protected int[] metadatalibsTreeSelectionRows;

    private int[] updateSelectionRows(javax.swing.event.TreeSelectionEvent evt) {
        JTree treeSource = (JTree) evt.getSource();
        return treeSource.getSelectionRows();
    }
    // end

    @Override
    public void layout() {
        super.layout(); //To change body of generated methods, choose Tools | Templates.
    }

    // *************************************************************************
    // Kotlin override functions
    protected TableModel buildSearchResultModel() {
        return new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {"Empty", "None"},
                    {"No empty", "1"}
                },
                new String[]{
                    "Result : ", "Match on : "
                }
        );
    }
    
    protected TableModel buildSearchResultModel(Object[][] data){
        return new javax.swing.table.DefaultTableModel(data, new String[]{"Result ", "Match on: "});
    }

    protected void setRightPreviewLabelContent(String text) {
        if (text != null) {
            this.RightPreviewLabel.setText(text);
        }
    }

    protected void setRightPreviewLabelContent(BufferedImage img) {
        if (img != null) {
            Image dimg = img.getScaledInstance(this.RightPreviewLabel.getWidth(), this.RightPreviewLabel.getHeight(), Image.SCALE_SMOOTH);
            this.RightPreviewLabel.setIcon(new ImageIcon(dimg));
        }
    }
    // end

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Install theme */
        FlatSolarizedLightIJTheme.install();
        //FlatDarculaLaf.install();
        //FlatIntelliJLaf.install();
        //FlatCyanLightIJTheme.install();
        //FlatHiberbeeDarkIJTheme.install();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KtmetaMainFrameDesign().setVisible(true);
            }
        });
    }
    
    //<My-Custom>
    private void setIcon(){
        Image img = new ImageIcon(getClass().getResource("/imgs/LOGO.png")).getImage();
        this.setIconImage(img);
    }
    
    //</My-Custom>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton BTNAddDatabase;
    protected javax.swing.JButton BTNAddESIndex;
    protected javax.swing.JButton BTNAddMetaLib;
    protected javax.swing.JButton BTNGotoFirstPage;
    protected javax.swing.JButton BTNGotoLastPage;
    protected javax.swing.JButton BTNGotoNextPage;
    protected javax.swing.JButton BTNGotoPreviousPage;
    protected javax.swing.JButton BTNQQueryHelper;
    protected javax.swing.JButton BTNQuickQuerySearch;
    protected javax.swing.JButton BTNRefresh;
    protected javax.swing.JButton BTNRightPreviewEnlargeShotcut;
    protected javax.swing.JPanel BottomPanel;
    private javax.swing.ButtonGroup ButtonGroupOnAttr;
    private javax.swing.ButtonGroup ButtonGroupOnWhere;
    protected javax.swing.JCheckBox CheckBoxQQueryCreateNewTab;
    protected javax.swing.JCheckBox CheckBoxQQueryOnDB;
    protected javax.swing.JCheckBox CheckBoxQQueryOnES;
    protected javax.swing.JComboBox<String> ComboBoxQQueryAvailableMetaLibs;
    protected javax.swing.JMenu EditMenu;
    protected javax.swing.JMenu FileMenu;
    protected javax.swing.JMenu HelpMenu;
    private javax.swing.JLabel LabelQQueryOnMetaLib;
    private javax.swing.JLabel LabelQQuerySearch;
    protected javax.swing.JLabel LabelResultRows;
    private javax.swing.JLabel LabelRightAbstract;
    private javax.swing.JLabel LabelRightPreview;
    private javax.swing.JLabel LabelRightTags;
    protected javax.swing.JMenuBar MainMenuBar;
    protected javax.swing.JSplitPane MainSplitPane;
    protected javax.swing.JToolBar MainToolBar;
    protected javax.swing.JMenuItem MenuItemAbout;
    protected javax.swing.JMenuItem MenuItemAddDatabase;
    protected javax.swing.JMenuItem MenuItemAddIndex;
    protected javax.swing.JMenuItem MenuItemExit;
    protected javax.swing.JMenuItem MenuItemNewMetaLib;
    protected javax.swing.JMenuItem MenuItemScanMetas;
    protected javax.swing.JMenuItem MenuItemSettings;
    protected javax.swing.JMenuItem PMAbstractCopyAll;
    private javax.swing.JMenuItem PMAbstractCopySelected;
    protected javax.swing.JMenuItem PMDBPropertiesEdit;
    protected javax.swing.JMenuItem PMDetailsExportToFile;
    protected javax.swing.JMenuItem PMExportDatabaseData;
    protected javax.swing.JMenuItem PMExportJSON;
    protected javax.swing.JMenuItem PMImportDataToDB;
    protected javax.swing.JMenuItem PMIndexPropertiesEdit;
    protected javax.swing.JMenuItem PMMetaLibProperties;
    protected javax.swing.JMenuItem PMRemoveDatabase;
    protected javax.swing.JMenuItem PMRemoveIndex;
    protected javax.swing.JMenuItem PMRemoveMetaLib;
    protected javax.swing.JMenuItem PMRenameDatabase;
    protected javax.swing.JMenuItem PMRenameIndices;
    protected javax.swing.JMenuItem PMRenameMetaLib;
    protected javax.swing.JMenuItem PMSyncToES;
    protected javax.swing.JMenuItem PMTagsAddCustom;
    protected javax.swing.JMenuItem PMTagsCopyAll;
    protected javax.swing.JMenuItem PMTagsCopySelected;
    protected javax.swing.JMenuItem PMViewEnlarge;
    protected javax.swing.JPanel PanelInfoOutput;
    protected javax.swing.JTabbedPane PanelQuery;
    private javax.swing.JPanel PanelQuickQuery;
    protected javax.swing.JPanel PanelResultTemplate;
    protected javax.swing.JPanel PanelResultToolbar;
    protected javax.swing.JPanel PanelRightPreview;
    protected javax.swing.JPanel PanelSplitCenter;
    protected javax.swing.JPopupMenu PopupMenuAbstract;
    protected javax.swing.JPopupMenu PopupMenuDatabasesTree;
    protected javax.swing.JPopupMenu PopupMenuIndicesTree;
    protected javax.swing.JPopupMenu PopupMenuMetaLibsTree;
    protected javax.swing.JPopupMenu PopupMenuMetadataDetails;
    protected javax.swing.JPopupMenu PopupMenuPreview;
    protected javax.swing.JPopupMenu PopupMenuTags;
    protected javax.swing.JPanel RightDetailsPane;
    private javax.swing.JLabel RightLabelMetadataDoc;
    protected javax.swing.JLabel RightPreviewLabel;
    protected javax.swing.JTextPane RightTextPaneAbstract;
    protected javax.swing.JTextPane RightTextPaneMetaDoc;
    protected javax.swing.JTextPane RightTextPaneTags;
    private javax.swing.JScrollPane SRPScrollPane;
    protected javax.swing.JSpinner SpinnerMaxRows;
    private javax.swing.JPanel SplitPaneSubLeft;
    protected javax.swing.JSplitPane SplitPaneSubRight;
    private javax.swing.JSplitPane SplitPaneSubVTLeft;
    protected javax.swing.JSplitPane SplitPaneVTGeneral;
    private javax.swing.JTabbedPane SubLeftDown;
    private javax.swing.JTabbedPane SubLeftUpTab;
    protected javax.swing.JTabbedPane TabbedPaneQueryResult;
    protected javax.swing.JTabbedPane TabbedPaneSplitRight;
    protected javax.swing.JTable TableResult;
    protected javax.swing.JTextField TextFieldQQuerySearch;
    protected javax.swing.JPanel ToolBarPanel;
    protected javax.swing.JMenu ToolsMenu;
    private javax.swing.JTree TreeDatabases;
    private javax.swing.JTree TreeIndices;
    private javax.swing.JTree TreeMetadataLibs;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JToolBar.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
